<div id="count"></div>
<script>
$(function(){
	Collections.Groups
		.getInstance()
		.onAdd(function(model){
			new Views.MoneyFlowGroup(model)
		})
		.addBunch(<?=json_encode($this->groups)?>);

	Collections.Categories
		.getInstance()
		.addBunch(<?=json_encode($this->categories)?>);
});
</script>
<?php
Libs_Views::create('/elements/category.phtml')->render();

Libs_Views::create('/elements/group.phtml')
	->assign('show_menu', false)
	->render();

Libs_Views::create('/elements/context_menu.phtml')
	->assign('id', 'categories-context-menu')
	->assign('items', array(
				'withdrawal' => _t('/context_menu/withdrawal'),
				'return-amount' => _t('/context_menu/return_amount')
			))
	->render();
?>