<div id="count"></div>
<script>
i18n["/dialogs/titles/add_group"] = "<?=_t('/js/dialogs/titles/add_group')?>";
i18n["/dialogs/titles/add_category"] = "<?=_t('/js/dialogs/titles/add_category')?>";
i18n["/dialogs/titles/edit_category"] = "<?=_t('/js/dialogs/titles/edit_category')?>";
i18n["/dialogs/titles/edit_group"] = "<?=_t('/js/dialogs/titles/edit_group')?>";
i18n["/dialogs/text/delete_group"] = "<?=_t('/js/dialogs/text/delete_group')?>";
i18n["/dialogs/text/delete_category"] = "<?=_t('/js/dialogs/text/delete_category')?>";

$(function(){
	Collections.Groups.getInstance().addBunch(<?=json_encode($this->groups)?>);
	Collections.Categories.getInstance().addBunch(<?=json_encode($this->categories)?>);

	Collections.Groups.getInstance().each(function(model){
		Views.GroupsCollection.getInstance().add(model.get("id"), new Views.Group(model));
	});

	new Views.AddGroupInitiator();
});
</script>

<script id="add-group-dialog" type="text/template">
<div class="form">
	<form action="<?=_url('/PlannerProcessor/addGroup/');?>">
	<?php Libs_Views::create('planner/group_fields.phtml')->render()?>
	</form>
	</div>
</script>

<script id="edit-group-dialog" type="text/template">
<div class="form">
	<form action="<?=_url('/PlannerProcessor/editGroup/');?>">
	<?php Libs_Views::create('planner/group_fields.phtml')->render()?>
	</form>
	</div>
</script>

<script type="text/template" id="category-template">
<tr class="group-categories">
<td>
	 <span class="tab-menu cat-item" data-field="title">{{title}}</span>
</td>
<td class="tdrg" data-field="amount">{{amount}}</td>
</tr>
</script>

<script type="text/template" id="group-template">
<table class="count_tb count_tb_ex">
<tr class="group-title">
	<th>
		<span class="tab-menu group-item" data-field="name">{{name}}</span>
	</th>
	<th><?=_t('/money_flow/sum')?></th>
</tr>
<tr id="categories-hook">
	<td colspan="2" class="tdbg"></td>
</tr>
</table>
</script>

<script type="text/template" id="groups-context-menu">
	<div class="info-menu">
		<a href="#" action="add-category"><?=_t('/context_menu/add_category')?></a>
		<br/>
 		<a href="#" action="edit-group"><?=_t('/context_menu/edit')?></a>
		<br/>
		<a href="#" action="delete-group"><?=_t('/context_menu/delete')?></a>
	</div>
</script>
<script type="text/template" id="categories-context-menu">
	<div class="info-menu">
		<a href="#" action="edit-category"><?=_t('/context_menu/edit')?></a>
		<br/>
		<a href="#" action="delete-category"><?=_t('/context_menu/delete')?></a>
	</div>
</script>

<script id="add-category-dialog" type="text/template">
<div class="form" id="dialog-content">
<form action="<?=_url('/PlannerProcessor/addCategory/')?>">
<?php Libs_Views::create('planner/category_fields.phtml')->render()?>
</form>
</div>
</script>

<script id="edit-category-dialog" type="text/template">
<div class="form" id="dialog-content">
<form action="<?=_url('/PlannerProcessor/editCategory/')?>">
<?php Libs_Views::create('planner/category_fields.phtml')->render()?>
</form>
</div>
</script>