<div id="count"></div>
<script>
$(function(){
	Collections.Groups.getInstance().addBunch(<?=json_encode($this->groups)?>);
	Collections.Categories.getInstance().addBunch(<?=json_encode($this->categories)?>);

	Collections.Groups.getInstance().each(function(model){
		new Views.Group(model);
	});
});
</script>

<script type="text/template" id="category-template">
<tr class="group-categories">
<td>
	 <span class="tab-menu cat-item" data-field="title">{{title}}</span>
</td>
<td class="tdrg" data-field="amount">{{amount}}</td>
</tr>
</script>

<script type="text/template" id="group-template">
<table class="count_tb count_tb_ex">
<tr class="group-title">
	<th>
		<span class="tab-menu group-item" data-field="name">{{name}}</span>
	</th>
	<th><?=_t('/money_flow/sum')?></th>
</tr>
<tr id="categories-hook">
	<td colspan="2" class="tdbg"></td>
</tr>
</table>
</script>

<script type="text/template" id="groups-context-menu">
	<div class="info-menu">
		<a href="#" action="add-category"><?=_t('/context_menu/add_category')?></a>
		<br/>
 		<a href="#" action="edit-group"><?=_t('/context_menu/edit')?></a>
		<br/>
		<a href="#" action="delete-group"><?=_t('/context_menu/delete')?></a>
	</div>
</script>
<script type="text/template" id="categories-context-menu">
	<div class="info-menu">
		<a href="#" action="edit-category"><?=_t('/context_menu/edit')?></a>
		<br/>
		<a href="#" action="delete-category"><?=_t('/context_menu/delete')?></a>
	</div>
</script>

<script id="add-category-dialog" type="text/template">
<div class="form" id="dialog-content">
<form action="<?=_url('/PlannerProcessor/addCategory/')?>">
<table>
	<tr>
		<td>
			Название:*
		</td>
		<td>
			<input type="text" name="title" />
		</td>
	</tr>
	<tr>
		<td>
			Сумма:
		</td>
		<td>
			<input type="text" name="amount" />
		</td>
	</tr>
	<tr>
		<td>
			Группа:
		</td>
		<td>
			<select id="groups-select" name="group">
			<?php
				foreach($this->groups as $item)
				{
					echo '<option value="'.$item['id'].'">'.$this->escape($item['name']).'</option>';
				}
			?>
			</select>
		</td>
	</tr>
	<tr>
		<td>
			Прикрепить:
		</td>
		<td>
			<input type="checkbox" name="pin" value="1" />
		</td>
	</tr>
</table>
</form>
</div>
</script>