<script id="<?=$this->id?>" type="text/template">
<div class="form">
	<form action="<?=$this->url?>">
	<table>
		<tr>
			<td>
				<?=_t('/dialogs/money_flow/amount');?>:
			</td>
			<td>
				<input type="text" name="amount" />
			</td>
		</tr>
		<tr>
			<td>
				<?=_t('/dialogs/money_flow/comments');?>:
			</td>
			<td>
				<textarea style="resize: none;" name="comment"></textarea>
			</td>
		</tr>
	</table>
	</form>
	</div>
</script>