 <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title ?></title>
        <link rel="stylesheet" href="/front/css/main.css" />
        <script src="/front/js/vendor/jquery.js"></script>
		<script src="/front/js/vendor/underscore-min.js"></script>
		<script src="/front/js/vendor/class.js"></script>
		<script src="/front/js/main.js"></script>
		<?=load_js($_GET['controller'], $_GET['action']); ?>
    </head>