 <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?=$this->title ?></title>
        <link rel="stylesheet" href="/front/css/main.css" />
        <script src="<?=_url('/FrontI18n/')?>"></script>
        <script src="/front/js/jquery.js"></script>
		<script src="/front/js/underscore-min.js"></script>
		<script src="/front/js/common.js"></script>
		<script src="/front/js/models.js"></script>
		<script src="/front/js/views.js"></script>
    </head>