<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>New Web Project</title>
        <link rel="stylesheet" href="/front/css/main.css" />
    </head>
    <body>
           <div id="tp"></div>
        <div id="content">
        	<div id="header-top">
        		 <div id="tp-left">
	                Остаток: 2300000.00
	            </div>
	            <div id="tp-right">
	                <b>Бюджет:</b> 300000.00 &nbsp;&nbsp;
	                <b>Расходы:</b> 23300.00
	                (<a href="#"><?=_t('/menu/settings')?></a> - <a href="<?=_url('/AuthProcessor/signout/');?>"><?=_t('/auth/exit')?></a>)
	            </div>
	            <br class="clr" />
        	</div>
            <div id="header">
                <div id="hd-left">Манипулятор</div>
                <div id="menu">

                        <a href="#">Внести сумму</a>
                        <a href="#">Забрать сумму</a>
                        <a href="#" id="last">Новый месяц</a>
                 </div>
               <br class="clr" />
            </div>
            <div id="left">
                <ul>
                    <li class="select">
                        <a href="#">Манипулятор</a>
                    </li>
                    <li>
                        <a href="#">Планнер</a>
                    </li>
                    <li>
                        <a href="#">История операций</a>
                    </li>
                    <li>
                        <a href="#">Архив</a>
                    </li>
                </ul>
            </div>
            <div id="right">
                <div id="count">
                    <div id="nav">
                <a href="#">Вернуть</a>&nbsp;|&nbsp;<a href="#">Отменить</a>
            </div>
                <table class="count_tb count_tb_ex">
                    <tr>
                        <th>
                            <span class="tab-menu">Описание</span>
                        </th>
                        <th>
                            Сумма
                        </th>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Кисина поездка к родным
                                 <div class="info-menu">
                                     <a href="#"><b>Забрать сумму</b></a>
                                     <a href="#"><b>Сбалансировать</b></a>
                                 </div>
                             </span>
                        </td>
                        <td class="tdrg">
                            6
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Кисин обед</span>
                        </td>
                        <td class="tdrg">
                            200
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Поезка на работу</span>
                        </td>
                        <td class="tdrg">
                            400
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Киичкина прическа</span>
                        </td>
                        <td class="tdrg">
                           1000
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="tdbg"> </td>
                    </tr>
                </table>

                <table class="count_tb count_tb_ex">
                    <tr>
                        <th>
                            <span class="tab-menu">Описание</span>
                        </th>
                        <th>
                            Сумма
                        </th>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Солнышкина поезка в село
                              </span>
                        </td>
                        <td class="tdrg">
                            200
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Солнышкин обед</span>
                        </td>
                        <td class="tdrg">
                            200
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Поездка на работу</span>
                        </td>
                        <td class="tdrg">
                            120
                        </td>
                    </tr>
                    <tr>
                        <td>
                             <span class="tab-menu">Солнышкина прическа</span>
                        </td>
                        <td class="tdrg">
                           45
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="tdbg"> </td>
                    </tr>
                </table>
            </div>
        </div>
            <div id="footer">
                Kisya &amp; Solnyshko Co. All rights reserved. 2012
            </div>
        </div>
    </body>
</html>