<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	 <?php
   		Libs_Views::create('header.phtml')
   			->assign('title', $this->title)
   			->render();
  	 ?>
    <body>
           <div id="tp"></div>
        <div id="content">
        	<div id="header-top">
        		 <div id="tp-left">
	                Остаток: 2300000.00
	            </div>
	            <div id="tp-right">
	                <b>Бюджет:</b> 300000.00 &nbsp;&nbsp;
	                <b>Расходы:</b> 23300.00
	                (<a href="#"><?=_t('/menu/settings')?></a> - <a href="<?=_url('/AuthProcessor/signout/');?>"><?=_t('/auth/exit')?></a>)
	            </div>
	            <br class="clr" />
        	</div>
            <div id="header">
                <div id="hd-left"><?php
                	if (is_location('/MoneyFlow/*/'))
                	{
						echo _t('/sections/money_flow');
                	}
                	elseif(is_location('/Planner/*/'))
                	{
                		echo _t('/sections/planner');
                	}
                	elseif(is_location('/Logs/*/'))
                	{
                		echo _t('/sections/logs');
                	}
                	elseif(is_location('/Archive/*/'))
                	{
                		echo _t('/sections/archive');
                	}
                	else
                	{
                		echo _t('/sections/money_flow');
                	}
                ?></div>
                <div id="menu">
                        <a href="#">Внести сумму</a>
                        <a href="#">Забрать сумму</a>
                        <a href="#" id="last">Новый месяц</a>
                 </div>
               <br class="clr" />
            </div>
            <div id="left">
                <ul>
                    <li <?=is_location('/MoneyFlow/*/')? 'class="select"' : ''?>>
                        <a href="<?=_url('/MoneyFlow/')?>"><?=_t('/sections/money_flow')?></a>
                    </li>
                    <li <?=is_location('/Planner/*/')? 'class="select"' : ''?>>
                        <a href="<?=_url('/Planner/')?>"><?=_t('/sections/planner')?></a>
                    </li>
                    <li <?=is_location('/Logs/*/')? 'class="select"' : ''?>>
                        <a href="<?=_url('/Logs/');?>"><?=_t('/sections/logs');?></a>
                    </li>
                    <li <?=is_location('/Archive/*/')? 'class="select"' : ''?>>
                        <a href="<?=_url('/Archive/');?>"><?=_t('/sections/archive');?></a>
                    </li>
                </ul>
            </div>
            <div id="right">
            	<?=$this->view->render()?>
            </div>
            <div id="footer">
                Kisya &amp; Solnyshko Co. All rights reserved. 2012
            </div>
        </div>
    </body>
</html>